MeetForce/force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>An object representing individual Meetup instances and relating meetup registrations.</description>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MeetForce/force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>A randomly generated code to identify a meetup in a more user-readable format.</description>
    <externalId>true</externalId>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

MeetForce/force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <label>Registration Limit</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MeetForce/force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Whether the Meetup is allowing new registrations (open) or not (closed).</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MeetForce/force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Individual registrations from people for meetups. Emails must be unique per meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>MR-{MM}{DD}{0000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MeetForce/force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address of the registering meetup participant.</description>
    <inlineHelpText>Meetup registrations for the same meetup cannot share the same email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

MeetForce/force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First name of the registering meetup participant.</description>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MeetForce/force-app/main/default/objects/MeetupRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last name of the registering meetup participant.</description>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MeetForce/force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>Meetup the Registration is for.</description>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

MeetForce/force-app/main/default/classes/MeetupRegistrationHelperTest.cls
@isTest
class MeetupRegistrationHelperTest {
    @TestSetup
    static void makeData() {
        List<Meetup__c> meetups = new List<Meetup__c>();
        for (Integer i = 0; i < 200; i++)
            meetups.add(new Meetup__c(Name = 'TestMeetup' + i, RegistrationLimit__c = 8));
        
        insert meetups;
    }
    @isTest
    static void generateRegistrationCodesTest() {
        List<String> regCodes = new List<String>();
        Boolean noRepeats = true;
        Integer i = 0;
        
        Test.startTest();
        List<Meetup__c> meetups = [SELECT RegistrationCode__c FROM Meetup__c WHERE Status__c = 'Open'];
        while (noRepeats && i < meetups.size()) {
            if (regCodes.contains(meetups.get(i).RegistrationCode__c))
                noRepeats = false;
            else regCodes.add(meetups.get(i).RegistrationCode__c);
            i++;
        }
        Test.stopTest();

        System.assertEquals(8, meetups.get(0).RegistrationCode__c.length());
        System.assert(noRepeats);
    }
    @isTest
    static void getMeetupIdByRegistrationCodeTest() {
        Test.startTest();
        Meetup__c meetup = [SELECT Id, RegistrationCode__c FROM Meetup__c LIMIT 1];
        Id fetchedId = MeetupRegistrationHelper.getMeetupIdByRegistrationCode(meetup.RegistrationCode__c);
        Test.stopTest();

        System.assertEquals(meetup.Id, fetchedId);
    }
    @isTest
    static void registrationIsOpenTest() {
        Test.startTest();
        List<Meetup__c> meetups = [SELECT Id, Status__c, RegistrationLimit__c FROM Meetup__c WHERE Status__c = 'Open' LIMIT 3];
        meetups.get(1).Status__c = 'Closed';
        meetups.get(2).RegistrationLimit__c = 0;
        update meetups;

        List<String> responses = new List<String>();
        for (Meetup__c meetup: meetups) {
            responses.add(MeetupRegistrationHelper.registrationIsOpen(meetup.Id));
        }
        Test.stopTest();

        System.assertEquals('This Meetup is open.', responses.get(0));
        System.assertEquals('This Meetup is closed.', responses.get(1));
        System.assertEquals('This Meetup is currently at its maximum number of registrations.', responses.get(2));
    }
    @isTest
    static void verifyUniqueEmailTest() {
        String errorMessage;
        Test.startTest();
        Meetup__c meetup = [SELECT Id FROM Meetup__c LIMIT 1];
        MeetupRegistration__c reg1 = new MeetupRegistration__c(FirstName__c = 'John', LastName__c = 'Johnson',
            Email__c = 'jj@jj.com', Meetup__c = meetup.Id);

        MeetupRegistration__c reg2 = new MeetupRegistration__c(FirstName__c = 'John', LastName__c = 'Johnson',
            Email__c = 'jj@jj.com', Meetup__c = meetup.Id);

        insert reg1;
        try {
            insert reg2;
        } catch (DMLException e) {
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        System.assertNotEquals(null, reg1.Id);
        System.assertEquals(null, reg2.Id);
        System.assertEquals(
            'Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Meetup Registrations of the same Meetup must have unique email addresses.',
            errorMessage);
    }
}