MeetForce/force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>An object representing individual Meetup instances and relating meetup registrations.</description>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MeetForce/force-app/main/default/objects/Meetup__c/fields/NumberOfRegistrations__c.field-meta.xml
<CustomField>
    <fullName>NumberOfRegistrations__c</fullName>
    <description>Number of related registrations.</description>
    <label>Number of Registrations</label>
    <summaryForeignKey>MeetupRegistration__c.Meetup__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

MeetForce/force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>A randomly generated code to identify a meetup in a more user-readable format.</description>
    <externalId>true</externalId>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

MeetForce/force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <label>Registration Limit</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MeetForce/force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Whether the Meetup is allowing new registrations (open) or not (closed).</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MeetForce/force-app/main/default/classes/MeetupRegistrationHelper.cls
public with sharing class MeetupRegistrationHelper {
    /*
    * Registration codes are generated using the Crypto class to keep code short and easily maintainable.
    * The smallest AES key is 16 characters, so a temporary string variable is used to store each generated
    * key which is split in four to serve as up to four registration codes and save performance.
    */
    public static void generateRegistrationCodes(List<Meetup__c> meetups) {
        String regCode;
        for (Integer i = 0; i < meetups.size(); i++) {
            switch on Math.mod(i,4) {
                when 0 {
                    regCode = EncodingUtil.convertToHex(Crypto.generateAesKey(128));
                    meetups.get(i).RegistrationCode__c = regCode.substring(0, 8);
                }
                when 1 {meetups.get(i).RegistrationCode__c = regCode.substring(8, 16);}
                when 2 {meetups.get(i).RegistrationCode__c = regCode.substring(16, 24);}
                when 3 {meetups.get(i).RegistrationCode__c = regCode.substring(24, 32);}
            }
        }
    }
    /*
    * Fetches a single meetup matching the registration code provided.
    * Sends an error message if that meetup is closed or full.
    */
    /*@AuraEnabled (cacheable=true)
    public static Meetup__c getMeetupByRegistrationCode(String regCode) {
        Meetup__c meetup = [SELECT Id, Name, RegistrationLimit__c, NumberOfRegistrations__c, Status__c
            FROM Meetup__c WHERE RegistrationCode__c =: regCode LIMIT 1];

        if (meetup.NumberOfRegistrations__c >= meetup.RegistrationLimit__c)
            throw new AuraHandledException('This Meetup is currently at its maximum number of registrations.');

        if (meetup.Status__c == 'Closed')
            throw new AuraHandledException('This Meetup is closed.');

        return meetup;
    }*/
    @AuraEnabled (cacheable=true)
    public static String registrationIsOpen(Id recordId) {
        Meetup__c meetup = [SELECT RegistrationLimit__c, NumberOfRegistrations__c, Status__c
        FROM Meetup__c WHERE Id =: recordId];

        if (meetup.NumberOfRegistrations__c >= meetup.RegistrationLimit__c)
            return 'This Meetup is currently at its maximum number of registrations.';

        if (meetup.Status__c == 'Closed')
            return 'This Meetup is closed.';

        return 'This Meetup is open.';
    }
}